### ISSUE TITLE
Won't read any GIF under Windows

### ISSUE THREAD

**Issue by fire-eggs** [wcout/fltk-gif-animation#1]
Just getting started but so far this project is looking fantastic!!

A blocker for Windows users: in `Fl_Anim_GIF_Image.cxx`, in the function `readin`, the following line (at or about line 548):
```
  FILE *gif = fopen(name_, "r");
```
needs to be changed to:
```
  FILE *gif = fopen(name_, "rb");
```
Without the binary flag, Windows will stop reading at the first zero byte.

**Comment by wcout** [comment]
Thank you very much for  the report.
