### ISSUE TITLE
Cannot load the attached animated GIF image

### ISSUE THREAD

**Issue by fire-eggs** [wcout/fltk-gif-animation#3]
As alluded to in issue #2, the attached animated GIF image cannot be loaded by Fl_Anim_GIF_Image.

[0_bfKvMYVWUpbBtXM5.zip](https://github.com/wcout/fltk-gif-animation/files/4926990/0_bfKvMYVWUpbBtXM5.zip)

**Comment by fire-eggs** [comment]
Fails attempting to load the first frame. The following test in gif_loadh.h, _GIF_LoadFrame fails:
```
    if ((ctbl = (1L << ctsz)) != (mask & _GIF_SWAP(*(GIF_H*)(*buff + 1))))
        return -2; /** initial code is not equal to min LZW size **/
```

Disabling that test allows the GIF to load and display. I don't know what the possible implications are of not using that test.

**Comment by hidefromkgb** [comment]
There shall be no implications whatsoever, I was just trying to be pedantic about the standard when adding this check.

**Comment by wcout** [comment]
I have now removed this check in my copy of gif_load.h. 
@hidefromkgb: Thanks for clarifying. I wouldn’t have dared to change anything otherwise.

**Comment by wcout** [comment]
Fixed in current repository. Thanks for the analysis!
